name: Flowby
description: Flowby is a close by community of people that share their skills in person.

version: 1.0.0+1

module:
  androidX: true

environment:
  sdk: '>=2.3.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  rxdart: ^0.23.1
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.3+1
  geolocator: ^5.2.1
  provider: ^4.0.3
  video_player: ^0.10.6
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.1.5+1
  flutter_icons: ^1.0.0+1
  cached_network_image: ^2.0.0
  share: ^0.6.3+5
  image_cropper: ^1.2.1
  flare_flutter: ^2.0.1
  google_sign_in: ^4.1.1
  apple_sign_in: ^0.1.0
  device_info: ^0.4.1+4
  equatable: ^1.0.0
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.6+1

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/

  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: NotoRegular
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
    - family: MuliRegular
      fonts:
        - asset: assets/fonts/Muli/static/Muli-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
    - family: NotoMedium
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
