name: Flowby
description: A new Flutter application.

version: 1.0.0+1

module:
  androidX: true

environment:
  sdk: '>=2.3.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.12.9+6
  firebase_storage: ^3.0.8
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.1+11
  geolocator: ^5.1.5
  provider: ^4.0.1
  rxdart: ^0.23.1
  video_player: ^0.10.5+1
  firebase_messaging: ^5.1.0
  flutter_local_notifications: ^0.9.1+3
  flutter_icons: ^1.0.0+1
  cached_network_image: ^2.0.0
  share: ^0.6.3+5
  image_cropper: ^1.2.0
  flare_flutter: any
  google_sign_in: ^4.1.1
  apple_sign_in: ^0.1.0
  device_info: ^0.4.1+4

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/

  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: NotoRegular
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
    - family: MuliRegular
      fonts:
        - asset: assets/fonts/Muli/static/Muli-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
