name: float
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.3.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+6
  firebase_storage: ^3.0.8
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.1+11
  geolocator: ^5.1.5
  provider: ^3.2.0
  rxdart: ^0.23.1
  video_player: ^0.10.5+1
  firebase_messaging: ^5.1.0

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: NotoRegular
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
