name: Flowby
description: Flowby is a close by community of people that share their skills in person.

version: 1.0.5+12

module:
  androidX: true

environment:
  sdk: '>=2.3.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: 0.4.4
  firebase_auth: 0.15.4
  rxdart: ^0.23.1
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.3+1
  geolocator: ^5.2.1
  provider: ^4.0.3
  video_player: ^0.10.6
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.4.0
  flutter_icons: ^1.0.0+1
  cached_network_image: ^2.0.0
  share: ^0.6.3+5
  image_cropper: ^1.2.1
  flare_flutter: ^2.0.1
  google_sign_in: ^4.1.1
  apple_sign_in: ^0.1.0
  device_info: ^0.4.1+4
  equatable: ^1.0.0
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.6+1
  liquid_swipe: ^1.3.1
  bot_toast: ^2.2.1
  flutter_typeahead: ^1.8.0
  algolia: ^0.1.7

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/
    - languages/en.json
    - languages/de.json
    - languages/fr.json
    - languages/it.json

  fonts:
    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
    - family: MontserratExtraLight
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
    - family: MontserratThin
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
    - family: MuliBlack
      fonts:
        - asset: assets/fonts/Muli/Muli-Black.ttf
    - family: MuliBold
      fonts:
        - asset: assets/fonts/Muli/Muli-Bold.ttf
    - family: MuliExtraBold
      fonts:
        - asset: assets/fonts/Muli/Muli-ExtraBold.ttf
    - family: MuliExtraLight
      fonts:
        - asset: assets/fonts/Muli/Muli-ExtraLight.ttf
    - family: MuliLight
      fonts:
        - asset: assets/fonts/Muli/Muli-Light.ttf
    - family: MuliMedium
      fonts:
        - asset: assets/fonts/Muli/Muli-Medium.ttf
    - family: MuliRegular
      fonts:
        - asset: assets/fonts/Muli/Muli-Regular.ttf
    - family: MuliSemiBold
      fonts:
        - asset: assets/fonts/Muli/Muli-SemiBold.ttf
